application: apptemplate
version: 1
runtime: python27
api_version: 1
threadsafe: true


libraries:
- name: jinja2
  version: 2.6

- name: pycrypto
  version: 2.6


handlers:
- url: /.*
  script: pkg_loader.app
  login: optional

